# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which your Express server is running (change accordingly if it's different)
EXPOSE 8000

# Command to run your Node.js application using ts-node
CMD ["npm", "run", "dev"]